練習問題7_1
表5
CREATE TABLE department(d_id INT AUTO_INCREMENT PRIMARY KEY,d_name VARCHAR(30) NOT NULL);
表6
CREATE TABLE worker(w_id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL,furigana VARCHAR(100) NOT NULL ,gender CHAR(1) DEFAULT 3, d_id INT NOT NULL ,FOREIGN KEY(d_id) REFERENCES department(d_id));


練習問題7_2
DROP TABLE worker;

CREATE TABLE worker(w_id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL,furigana VARCHAR(100) NOT NULL ,gender CHAR(1) NOT NULL DEFAULT 3, d_id INT NOT NULL ,FOREIGN KEY(d_id) REFERENCES department(d_id));